/**
 * Terms, refunds and cancellation, as data — lib/legal/policies.ts
 *
 * WHY THE TEXT IS DATA AND NOT JSX. Three reasons, in the order they matter:
 *
 *   IT CAN BE TESTED. `legal-pages.test.ts` asserts that the refund policy does not promise
 *   a self-service refund, because there is no refund endpoint, no refund model and no
 *   Razorpay refund call anywhere in this repository — refunds are a human action in
 *   Razorpay's dashboard. A policy describing a more generous product than the code will
 *   deliver is the exact failure mode CLAUDE.md records for the stale trial-allowance note.
 *
 *   ONE SHAPE FOR ALL OF THEM, so a fourth policy cannot arrive with a different structure
 *   and quietly lose the draft banner.
 *
 *   THE NAME IS NEVER TYPED. `${BRAND.name}` is interpolated at render. CLAUDE.md: the name
 *   lived in 33 files, has been renamed twice, and lives in lib/brand.ts now.
 *
 * DRAFT IS PART OF THE DATA, not a comment. The page cannot render this wording without also
 * rendering the caveat — the same rule the DPDP disclosure already follows. Every sentence
 * here describes what the system actually does, verified against the code; none of it is a
 * legal judgement, and a lawyer has not seen it.
 *
 * WHAT A LAWYER STILL HAS TO DECIDE is listed at the bottom of each policy, so the review is
 * a short conversation about specific questions rather than a request to read a document.
 */

export interface PolicySection {
  heading: string;
  /** Paragraphs. Rendered in order, plain text — no markup, so nothing can be injected. */
  body: string[];
}

export interface Policy {
  slug: 'terms' | 'refund';
  title: string;
  /** One line under the title. */
  summary: string;
  /** Always true until a lawyer has adopted the wording. See the module note. */
  draft: true;
  /** ISO date this wording was last edited, shown so a reader can judge its age. */
  updated: string;
  sections: PolicySection[];
  /** The specific questions a lawyer needs to answer. Rendered, not hidden. */
  needsLegalReview: string[];
}

/** How long we say we will take. Kept here so both policies quote the same number. */
export const RESPONSE_WINDOW_DAYS = 7;

export const TERMS: Policy = {
  slug: 'terms',
  title: 'Terms of Service',
  summary: 'What you can expect from this service, and what it expects from you.',
  draft: true,
  updated: '2026-08-31',
  sections: [
    {
      heading: 'What this service is',
      body: [
        'This is interview practice software. It runs simulated interviews, group discussions and communication rounds, scores your answers, and writes you a report on how you did.',
        'It is practice. It is not a recruitment service, it does not place candidates with employers, and it has no relationship with any company whose interview process it simulates. Where a company or a role is named, that names the practice material — not an affiliation, endorsement or partnership.',
      ],
    },
    {
      heading: 'The assessment is generated by AI, and is not a certified evaluation',
      body: [
        'Every score, rating, readiness level and piece of written feedback is produced by an AI language model. It is generated automatically, it is not reviewed by a human before you see it, and it is not a certified, accredited or professionally validated assessment of your ability.',
        'It can be wrong. It can be wrong about facts, and it can be wrong about you — it may mark a correct answer down, miss something you got right, or produce feedback that does not fit what you actually said. Treat it as one practice signal among many.',
        'We give no guarantee about interview outcomes, placement, or the accuracy of any individual score. If a score matters to you and looks wrong, you can ask for a human to look at it — see the review and disputes section below.',
      ],
    },
    {
      heading: 'Your account',
      body: [
        'You need an account, and the details you give us must be your own and accurate. You are responsible for what happens under your account, so keep your password to yourself.',
        'The service is for people aged 18 and over. You confirm this at sign-up.',
        'One account is for one person. Sharing an account, reselling access, or running automated tools against the service are all grounds for suspension.',
      ],
    },
    {
      heading: 'What you upload, and what we do with it',
      body: [
        'You keep ownership of everything you upload — your resume, your answers, your recordings. You give us permission to process it for the purpose of running your practice sessions and producing your reports, and for nothing else.',
        'Running a session sends your text to third-party AI providers, some of which are outside India. Who they are, what they receive and which country they are in is listed on the privacy page, and is shown to you before your first resume upload.',
        'Do not upload anything you do not have the right to upload, and do not upload other people’s personal information.',
      ],
    },
    {
      heading: 'Paying for it',
      body: [
        'Sessions are bought individually or in packs. Prices are shown before you pay and are charged in Indian rupees through Razorpay. Card details are entered in Razorpay’s own payment sheet and never reach this service.',
        'What each pack includes is stated at the point of purchase. Purchased items do not expire on a fixed clock; if that ever changes, the change will apply only to purchases made afterwards.',
        'Refunds and cancellation are covered by the refund policy, which forms part of these terms.',
      ],
    },
    {
      heading: 'Review and disputes',
      body: [
        'If you believe a score or a piece of feedback is wrong, you can ask for it to be reviewed by a person. There is a dispute option on the report itself, and you can also write to the grievance officer.',
        'We will acknowledge a dispute and tell you the outcome. A review may correct the report, may explain why the score stands, or may credit the session back — it will not be resolved silently.',
      ],
    },
    {
      heading: 'What we do not promise',
      body: [
        'We try to keep the service available and working, and we do not promise it will be uninterrupted or error-free. It depends on third-party AI providers, and those can be slow or unavailable.',
        'To the extent the law allows, our liability for any claim connected to this service is limited to the amount you paid us for it in the twelve months before the claim.',
        'Nothing here limits liability that cannot be limited by law, including for fraud.',
      ],
    },
    {
      heading: 'Ending it',
      body: [
        'You can delete your account at any time from your settings. What is deleted and what is legally required to be kept is set out on the privacy page.',
        'We may suspend or close an account that breaks these terms. Where money has been paid for items not yet used, the refund policy applies.',
      ],
    },
    {
      heading: 'Governing law',
      body: [
        'These terms are governed by the laws of India, and the courts of India have jurisdiction over any dispute.',
      ],
    },
  ],
  needsLegalReview: [
    'The liability cap and its wording, against the Indian Contract Act and consumer protection law.',
    'Whether the 18+ self-declaration is sufficient for a product aimed at campus placement, where a meaningful share of first-year students are 17.',
    'The seat of jurisdiction, stated here only as "the courts of India".',
    'Whether the AI-assessment disclaimer is sufficient where a report may influence a real hiring decision.',
  ],
};

export const REFUND: Policy = {
  slug: 'refund',
  title: 'Refund and Cancellation Policy',
  summary: 'When you get your money back, how to ask, and how long it takes.',
  draft: true,
  updated: '2026-08-31',
  sections: [
    {
      heading: 'There is no subscription to cancel',
      body: [
        'This service does not sell subscriptions. You buy sessions or packs of sessions, one payment at a time, and nothing renews on its own.',
        'That means there is no recurring charge to stop and no cancellation deadline to miss. If you stop using the service, you stop being charged, because you were only ever charged when you chose to buy.',
        'If you simply want to stop, you do not need to tell us anything. You can delete your account from your settings whenever you like.',
      ],
    },
    {
      heading: 'When we will refund you',
      body: [
        'Anything you bought and have not used. If you have not started a session it is unused, and we will refund it on request.',
        'A session that failed because of us. If a session could not be completed, produced no report, or was cut short by a fault on our side, that session is refunded or credited back — you should not pay for something that did not run.',
        'A duplicate or accidental charge. If you were charged twice for the same thing, the extra charge is refunded in full.',
        'A charge you did not authorise. Tell us and tell your bank; we will refund it and cooperate with your bank’s process.',
      ],
    },
    {
      heading: 'When we usually will not',
      body: [
        'A session that ran, produced a report, and that you are unhappy with. The service is practice, and a low score is a result rather than a fault. If you think the score itself is wrong, ask for a human review instead — that route is free and is described in the terms.',
        'We would rather look at a specific complaint than apply a blanket rule, so if your situation does not fit neatly into either list above, write to us and say what happened.',
      ],
    },
    {
      heading: 'How to ask',
      body: [
        'Write to the grievance officer, whose contact is published on the grievance page. Include the email address on your account and roughly when the payment was made — that is enough for us to find it.',
        'You do not need a receipt, an order number or a particular form of words.',
      ],
    },
    {
      heading: 'How long it takes',
      body: [
        `We will acknowledge your request within ${RESPONSE_WINDOW_DAYS} business days and tell you the decision by then.`,
        'An approved refund is returned to the original payment method through Razorpay. Once we have issued it, how quickly it appears is your bank’s timing rather than ours — typically five to seven business days for a card, and it can be longer.',
        'Refunds are processed by hand rather than by an automatic button, which is why the response window above matters: we will always come back to you within it, even if the answer is a question.',
      ],
    },
  ],
  needsLegalReview: [
    'Whether the "used session" exclusion is enforceable against Indian consumer protection law for a digital service.',
    'Whether a stated refund window is required, and whether 7 business days meets it.',
    'Whether the policy meets Razorpay’s merchant requirements for a live account.',
  ],
};

export const POLICIES: Record<Policy['slug'], Policy> = {
  terms: TERMS,
  refund: REFUND,
};
