import { Sparkles } from 'lucide-react';

/**
 * "A machine wrote this" — components/report/AiAssessmentNotice.tsx
 *
 * WHY EVERY SCORE SURFACE CARRIES THIS. A report here states whether somebody is ready for a
 * job interview, as a number and a readiness level, and a language model produced it without
 * a human reading it first. A candidate can reasonably act on that — practise differently,
 * apply or not apply, conclude something about themselves — and the model can be wrong in
 * ways that have nothing to do with them: a misread transcript, a correct answer marked
 * down, feedback that does not fit the session.
 *
 * Nothing on screen said so. A number rendered in a confident typeface reads as a
 * measurement, and this product's whole design language is built to make the score the lit
 * element on the page — which makes it MORE authoritative-looking, not less.
 *
 * TWO VARIANTS, BECAUSE ONE SIZE WOULD BE WRONG SOMEWHERE.
 *
 *   `full` — the report itself, where somebody is reading a judgement about their
 *   employability. It gets the whole sentence and the route to a person.
 *
 *   `inline` — a dashboard tile, a history row, an analytics chart. Somebody who has already
 *   read the full notice does not need it restated at full weight six times; a repeated
 *   banner is a banner people stop seeing, which is the failure mode this exists to avoid.
 *   So the score keeps a short, permanent label instead.
 *
 * IT CANNOT BE TURNED OFF, EITHER WAY. A caveat somebody can hide is a caveat that is
 * absent for exactly the people who have decided they know what the number means — which
 * is why this takes no callback to close it and stores no per-viewer preference.
 */
export function AiAssessmentNotice({
  variant = 'inline',
  className = '',
}: {
  variant?: 'full' | 'inline';
  className?: string;
}) {
  if (variant === 'inline') {
    return (
      <p
        className={`flex items-center gap-1.5 text-xs text-muted-foreground ${className}`}
        data-testid="ai-assessment-notice"
      >
        <Sparkles className="h-3 w-3 shrink-0" aria-hidden />
        <span>AI-generated assessment — not a certified evaluation</span>
      </p>
    );
  }

  return (
    <div
      className={`rounded-xl border border-border bg-muted/30 p-4 text-sm ${className}`}
      data-testid="ai-assessment-notice"
    >
      <p className="flex items-start gap-2 leading-relaxed text-muted-foreground">
        <Sparkles className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
        <span>
          <strong className="font-semibold text-foreground">
            This assessment was generated by AI.
          </strong>{' '}
          It was produced automatically by a language model, was not reviewed by a person
          before you saw it, and is not a certified or accredited evaluation of your ability.
          It can be wrong — about a fact, or about you. Treat it as one practice signal, not
          a verdict.
        </span>
      </p>
    </div>
  );
}

export default AiAssessmentNotice;
