"""
Checking and consuming entitlement — services/billing/credits.py

THIS IS THE ONLY PLACE ENTITLEMENT IS DECIDED. Endpoints call `consume`; nothing else reads
allowances to make a decision. A second implementation — a convenience check somewhere that
"just" compares a count — is how a metered feature ends up free on one route.

## The model: trial once, then buy what you use

Entitlement for a feature is:

    trial allowance  +  everything purchased  -  everything consumed

All three are counts over an append-only ledger. There is no period, no renewal and no
stored balance.

**WHY THE PERIOD IS GONE, AND WHY THAT MADE THIS SIMPLER.** The subscription model this
replaced measured usage inside a rolling 30-day window, which meant `user_plans` had to
carry `period_start`/`period_end`, those had to roll forward lazily on read, and a dormant
user could be several periods behind and need a loop to catch up. Every one of those is a
place to be wrong about somebody's money.

Purchased items do not expire, so the window disappears and with it all of that machinery.
The balance is now a `SUM(delta)` over one table, which cannot drift from itself and needs
no scheduled job to reset. A user who buys five interviews in March and uses the last one
in September gets what they paid for, with no code doing anything clever to allow it.

## Why the paywall in the UI is not the control

Every metered endpoint is reachable directly with a valid token, and the user who has spent
their allowance is exactly the user with a reason to try. A disabled button costs an
attacker one `curl`. The UI may not show anything the server would refuse, and the server
refuses regardless of what the UI showed.

## Concurrency, which is the part that is easy to get wrong

The naive implementation is: count, compare, insert. Two requests that interleave between
the count and the insert both see the same balance and both pass — so a user with one
interview left, double-clicking Start, gets two. That is not theoretical: a double-submit
on a slow connection is the single most common way it happens, and the report generated by
the second one is the expensive half.

`SELECT ... FOR UPDATE` on the user's `user_plans` row closes it. That row exists per user
and is the natural serialisation point, so the second request blocks until the first has
committed its ledger row and can therefore see it. Concurrency is serialised per user and
nowhere else — one candidate starting an interview never blocks another.

The whole check-and-write must therefore be in ONE transaction. Callers must not commit
between `consume` and the work it paid for; `get_db` commits on success and rolls back on
error, which is what makes a failed AI call undo the charge.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime

import structlog
from fastapi import status
from sqlalchemy import func, select

from app.core.exceptions import AppError
from app.db.session import AsyncSession
from app.models.billing import CreditEvent, UserPlan
from app.services.billing.plans import (
    FEATURE_LABELS,
    FEATURE_LABELS_SINGULAR,
    FEATURES,
    trial_allowance,
)

logger = structlog.get_logger(__name__)

#: Ledger entry kinds. `delta` is signed, so a balance is one SUM.
#:
#: The trial is NOT a ledger row. It is a constant added to the sum, so changing it changes
#: what every existing account has left — which is the correct behaviour for a promotional
#: allowance and impossible if it had been granted as rows at signup.
KIND_PURCHASE = "purchase"
KIND_CONSUME = "consume"
KIND_GRANT = "grant"  # support/admin goodwill, and refunds


class CreditsExhaustedError(AppError):
    """
    The user has nothing left for this feature and must buy more.

    402 PAYMENT REQUIRED, not 403. The distinction is load-bearing for the client: 403 means
    "you may not do this", which is permanent and offers nothing, while 402 means "you may
    do this once you pay", which is a prompt with an action attached. The frontend routes
    this status straight to the purchase sheet, so getting it wrong shows a dead end where
    an offer belongs.

    `details` carries the machine-readable shape the paywall renders from, so the client
    never has to parse the message.
    """

    def __init__(self, feature: str, used_trial: bool) -> None:
        one = FEATURE_LABELS_SINGULAR.get(feature, feature)
        many = FEATURE_LABELS.get(feature, feature)
        super().__init__(
            message=(
                f"You have used your free {one}. Buy another to continue."
                if used_trial
                else f"You have no {many} left. Buy more to continue."
            ),
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            code="CREDITS_EXHAUSTED",
            details={"feature": feature, "trial_used": used_trial},
        )


@dataclass(frozen=True)
class FeatureBalance:
    feature: str
    label: str
    #: Trial allowance plus everything bought.
    granted: int
    used: int

    @property
    def remaining(self) -> int:
        return max(0, self.granted - self.used)


@dataclass(frozen=True)
class Balance:
    features: list[FeatureBalance]
    #: True once the account has consumed anything at all — drives "your free trial" copy,
    #: which should not appear to somebody who has been paying for months.
    trial_started: bool


async def _plan_row(db: AsyncSession, user_id: uuid.UUID, *, lock: bool) -> UserPlan:
    """
    The user's row, created on first sight.

    LAZY CREATION RATHER THAN A SIGNUP HOOK. Every user needs one and signup is not the only
    way a user appears — the Supabase sync in POST /auth/profile creates them, admin tooling
    creates them, a restored backup has them already. A row created on first read cannot be
    missed by any of those, and the alternative failure is a user who cannot start anything
    because a hook did not fire months ago.

    It carries no balance. Its only jobs now are to be the lock target that serialises
    concurrent consumption, and to record how the account was created.
    """
    stmt = select(UserPlan).where(UserPlan.user_id == user_id)
    if lock:
        stmt = stmt.with_for_update()
    row = await db.scalar(stmt)
    if row is None:
        row = UserPlan(user_id=user_id, source="signup")
        db.add(row)
        # Flushed, not committed — the caller owns the transaction, and on the consume path
        # this row is what the lock above is taken on.
        await db.flush()
    return row


async def _totals(db: AsyncSession, user_id: uuid.UUID) -> dict[str, int]:
    """
    Net ledger position per feature: purchases and grants minus consumption.

    One grouped query rather than one per feature — this runs inside the request that starts
    an interview, and three round trips to answer one question is three chances to be slow
    at the worst moment.
    """
    rows = await db.execute(
        select(CreditEvent.feature, func.coalesce(func.sum(CreditEvent.delta), 0))
        .where(CreditEvent.user_id == user_id)
        .group_by(CreditEvent.feature)
    )
    return {feature: int(total or 0) for feature, total in rows}


async def get_balance(db: AsyncSession, user_id: uuid.UUID) -> Balance:
    """
    What this user has left, per feature.

    Read-only and unlocked — this feeds the dashboard and the paywall copy, where a value one
    request out of date is harmless. `consume` does its own locked read and never trusts this.
    """
    await _plan_row(db, user_id, lock=False)
    net = await _totals(db, user_id)

    used_any = await db.scalar(
        select(func.count())
        .select_from(CreditEvent)
        .where(CreditEvent.user_id == user_id, CreditEvent.kind == KIND_CONSUME)
    )

    features = []
    for feature in FEATURES:
        # Trial is a constant, not rows — see the note on KIND_* above. So "granted" is the
        # trial plus whatever the ledger's positive entries add up to, and the net sum
        # already has consumption subtracted from it.
        purchased = await db.scalar(
            select(func.coalesce(func.sum(CreditEvent.delta), 0)).where(
                CreditEvent.user_id == user_id,
                CreditEvent.feature == feature,
                CreditEvent.delta > 0,
            )
        )
        granted = trial_allowance(feature) + int(purchased or 0)
        remaining = trial_allowance(feature) + net.get(feature, 0)
        features.append(
            FeatureBalance(
                feature=feature,
                label=FEATURE_LABELS[feature],
                granted=granted,
                used=max(0, granted - remaining),
            )
        )

    return Balance(features=features, trial_started=bool(used_any))


async def remaining_for(db: AsyncSession, user_id: uuid.UUID, feature: str) -> int:
    """How many of `feature` this user may still start. Unlocked; display only."""
    net = await _totals(db, user_id)
    return max(0, trial_allowance(feature) + net.get(feature, 0))


async def consume(
    db: AsyncSession,
    user_id: uuid.UUID,
    feature: str,
    *,
    session_id: uuid.UUID | None = None,
    detail: dict | None = None,
) -> None:
    """
    Spend one of `feature`, or refuse.

    Raises CreditsExhaustedError (402) when there is nothing left. Returns None on success,
    having added a ledger row to the CALLER'S transaction — deliberately not committed here.

    THE CALLER MUST COMMIT, AND MUST COMMIT THE WORK IN THE SAME TRANSACTION. That is the
    contract, and it is what makes this atomic rather than merely careful: if starting the
    interview fails after this point, the rollback takes the charge with it. Committing here
    would create a window in which the user has been charged for a session that does not
    exist, and that window is exactly where a 500 lands.
    """
    plan_row = await _plan_row(db, user_id, lock=True)
    if plan_row.is_banned:
        # Checked here as well as at the request boundary. This is the last gate before
        # something billable happens, and a banned account reaching it means an earlier
        # check was missed rather than that the ban should be ignored.
        raise AccountBannedError(plan_row.ban_reason or "")

    net = await _totals(db, user_id)
    remaining = trial_allowance(feature) + net.get(feature, 0)

    if remaining <= 0:
        used_trial = trial_allowance(feature) > 0
        logger.info(
            "credits_exhausted",
            user_id=str(user_id),
            feature=feature,
            trial=trial_allowance(feature),
            net=net.get(feature, 0),
        )
        raise CreditsExhaustedError(feature, used_trial)

    db.add(
        CreditEvent(
            created_at=datetime.now(UTC),
            user_id=user_id,
            feature=feature,
            kind=KIND_CONSUME,
            delta=-1,
            session_id=session_id,
            detail=detail,
        )
    )
    await db.flush()


async def grant(
    db: AsyncSession,
    user_id: uuid.UUID,
    feature: str,
    quantity: int,
    *,
    kind: str = KIND_PURCHASE,
    payment_ref: str | None = None,
    detail: dict | None = None,
) -> None:
    """
    Add `quantity` of `feature` to the ledger — a purchase, a refund, or admin goodwill.

    IDEMPOTENCY IS THE CALLER'S JOB AND IS NOT OPTIONAL. Razorpay redelivers a webhook until
    it gets a 2xx, so the same payment WILL arrive more than once; the webhook checks
    `payment_ref` against the ledger before calling this. It is recorded here so that check
    has something to look at, and so a disputed charge can be traced to a payment id.
    """
    if quantity <= 0:
        raise ValueError("grant quantity must be positive")
    db.add(
        CreditEvent(
            created_at=datetime.now(UTC),
            user_id=user_id,
            feature=feature,
            kind=kind,
            delta=quantity,
            payment_ref=payment_ref,
            detail=detail,
        )
    )
    await db.flush()


class AccountBannedError(AppError):
    """
    The account is banned for credential sharing.

    403 rather than 402: this is not something more money fixes, and routing it to the
    purchase sheet would be both wrong and insulting. The client sends it to the appeal
    page instead.
    """

    def __init__(self, reason: str = "") -> None:
        super().__init__(
            message=(
                "This account is suspended because it was used from two places at once. "
                "You can request a review."
            ),
            status_code=status.HTTP_403_FORBIDDEN,
            code="ACCOUNT_BANNED",
            details={"reason": reason, "appealable": True},
        )
