"""
Checking and consuming entitlement — services/billing/credits.py

THIS IS THE ONLY PLACE ENTITLEMENT IS DECIDED. Endpoints call `consume`; nothing else reads
allowances to make a decision. A second implementation — a convenience check somewhere that
"just" compares a count — is how a metered feature ends up free on one route.

## The model: trial once, then buy what you use

Entitlement for a feature is:

    trial allowance  +  everything purchased  -  everything consumed

All three are counts over an append-only ledger. There is no period, no renewal and no
stored balance.

**WHY THE PERIOD IS GONE, AND WHY THAT MADE THIS SIMPLER.** The subscription model this
replaced measured usage inside a rolling 30-day window, which meant `user_plans` had to
carry `period_start`/`period_end`, those had to roll forward lazily on read, and a dormant
user could be several periods behind and need a loop to catch up. Every one of those is a
place to be wrong about somebody's money.

Purchased items do not expire, so the window disappears and with it all of that machinery.
The balance is now a `SUM(delta)` over one table, which cannot drift from itself and needs
no scheduled job to reset. A user who buys five interviews in March and uses the last one
in September gets what they paid for, with no code doing anything clever to allow it.

## Why the paywall in the UI is not the control

Every metered endpoint is reachable directly with a valid token, and the user who has spent
their allowance is exactly the user with a reason to try. A disabled button costs an
attacker one `curl`. The UI may not show anything the server would refuse, and the server
refuses regardless of what the UI showed.

## Concurrency, which is the part that is easy to get wrong

The naive implementation is: count, compare, insert. Two requests that interleave between
the count and the insert both see the same balance and both pass — so a user with one
interview left, double-clicking Start, gets two. That is not theoretical: a double-submit
on a slow connection is the single most common way it happens, and the report generated by
the second one is the expensive half.

`SELECT ... FOR UPDATE` on the user's `user_plans` row closes it. That row exists per user
and is the natural serialisation point, so the second request blocks until the first has
committed its ledger row and can therefore see it. Concurrency is serialised per user and
nowhere else — one candidate starting an interview never blocks another.

The whole check-and-write must therefore be in ONE transaction. Callers must not commit
between `consume` and the work it paid for; `get_db` commits on success and rolls back on
error, which is what makes a failed AI call undo the charge.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime

import structlog
from fastapi import status
from sqlalchemy import func, select

from app.core.exceptions import AppError
from app.db.session import AsyncSession
from app.models.billing import CreditEvent, UserPlan
from app.services.billing.plans import (
    FEATURE_LABELS,
    FEATURE_LABELS_SINGULAR,
    FEATURES,
    trial_allowance,
)

logger = structlog.get_logger(__name__)

#: Ledger entry kinds. `delta` is signed, so a balance is one SUM.
#:
#: The trial is NOT a ledger row. It is a constant added to the sum, so changing it changes
#: what every existing account has left — which is the correct behaviour for a promotional
#: allowance and impossible if it had been granted as rows at signup.
KIND_PURCHASE = "purchase"
KIND_CONSUME = "consume"
KIND_GRANT = "grant"  # support/admin goodwill, and refunds


class CreditsExhaustedError(AppError):
    """
    The user has nothing left for this feature and must buy more.

    402 PAYMENT REQUIRED, not 403. The distinction is load-bearing for the client: 403 means
    "you may not do this", which is permanent and offers nothing, while 402 means "you may
    do this once you pay", which is a prompt with an action attached. The frontend routes
    this status straight to the purchase sheet, so getting it wrong shows a dead end where
    an offer belongs.

    `details` carries the machine-readable shape the paywall renders from, so the client
    never has to parse the message.
    """

    def __init__(self, feature: str, used_trial: bool) -> None:
        one = FEATURE_LABELS_SINGULAR.get(feature, feature)
        many = FEATURE_LABELS.get(feature, feature)
        super().__init__(
            message=(
                f"You have used your free {one}. Buy another to continue."
                if used_trial
                else f"You have no {many} left. Buy more to continue."
            ),
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            code="CREDITS_EXHAUSTED",
            details={"feature": feature, "trial_used": used_trial},
        )


@dataclass(frozen=True)
class FeatureBalance:
    feature: str
    label: str
    #: Trial allowance plus everything bought.
    granted: int
    used: int

    @property
    def remaining(self) -> int:
        return max(0, self.granted - self.used)


@dataclass(frozen=True)
class Balance:
    features: list[FeatureBalance]
    #: True once the account has consumed anything at all — drives "your free trial" copy,
    #: which should not appear to somebody who has been paying for months.
    trial_started: bool
    #: Operator account: not metered at all. Surfaced so the UI can say "unlimited" rather
    #: than render a countdown that never moves, which looks like a broken meter.
    unlimited: bool = False


async def _is_admin(db: AsyncSession, user_id: uuid.UUID) -> bool:
    """
    Is this an operator account?

    Read from `users.is_admin` rather than from anything on the billing tables, so there is
    one definition of "admin" in the system and granting someone admin cannot leave their
    metering behind in a stale state.
    """
    from app.models.user import User  # noqa: PLC0415

    return bool(await db.scalar(select(User.is_admin).where(User.id == user_id)))


async def _plan_row(db: AsyncSession, user_id: uuid.UUID, *, lock: bool) -> UserPlan:
    """
    The user's row, created on first sight.

    LAZY CREATION RATHER THAN A SIGNUP HOOK. Every user needs one and signup is not the only
    way a user appears — the Supabase sync in POST /auth/profile creates them, admin tooling
    creates them, a restored backup has them already. A row created on first read cannot be
    missed by any of those, and the alternative failure is a user who cannot start anything
    because a hook did not fire months ago.

    It carries no balance. Its only jobs now are to be the lock target that serialises
    concurrent consumption, and to record how the account was created.
    """
    stmt = select(UserPlan).where(UserPlan.user_id == user_id)
    if lock:
        stmt = stmt.with_for_update()
    row = await db.scalar(stmt)
    if row is None:
        row = UserPlan(user_id=user_id, source="signup")
        db.add(row)
        # Flushed, not committed — the caller owns the transaction, and on the consume path
        # this row is what the lock above is taken on.
        await db.flush()
    return row


async def _totals(db: AsyncSession, user_id: uuid.UUID) -> dict[str, int]:
    """
    Net ledger position per feature: purchases and grants minus consumption.

    One grouped query rather than one per feature — this runs inside the request that starts
    an interview, and three round trips to answer one question is three chances to be slow
    at the worst moment.
    """
    rows = await db.execute(
        select(CreditEvent.feature, func.coalesce(func.sum(CreditEvent.delta), 0))
        .where(CreditEvent.user_id == user_id)
        .group_by(CreditEvent.feature)
    )
    return {feature: int(total or 0) for feature, total in rows}


async def get_balance(db: AsyncSession, user_id: uuid.UUID) -> Balance:
    """
    What this user has left, per feature.

    Read-only and unlocked — this feeds the dashboard and the paywall copy, where a value one
    request out of date is harmless. `consume` does its own locked read and never trusts this.
    """
    await _plan_row(db, user_id, lock=False)
    net = await _totals(db, user_id)

    used_any = await db.scalar(
        select(func.count())
        .select_from(CreditEvent)
        .where(CreditEvent.user_id == user_id, CreditEvent.kind == KIND_CONSUME)
    )

    features = []
    for feature in FEATURES:
        # Trial is a constant, not rows — see the note on KIND_* above. So "granted" is the
        # trial plus whatever the ledger's positive entries add up to, and the net sum
        # already has consumption subtracted from it.
        purchased = await db.scalar(
            select(func.coalesce(func.sum(CreditEvent.delta), 0)).where(
                CreditEvent.user_id == user_id,
                CreditEvent.feature == feature,
                CreditEvent.delta > 0,
            )
        )
        granted = trial_allowance(feature) + int(purchased or 0)
        remaining = trial_allowance(feature) + net.get(feature, 0)
        features.append(
            FeatureBalance(
                feature=feature,
                label=FEATURE_LABELS[feature],
                granted=granted,
                used=max(0, granted - remaining),
            )
        )

    return Balance(
        features=features,
        trial_started=bool(used_any),
        unlimited=await _is_admin(db, user_id),
    )


async def remaining_for(db: AsyncSession, user_id: uuid.UUID, feature: str) -> int:
    """How many of `feature` this user may still start. Unlocked; display only."""
    net = await _totals(db, user_id)
    return max(0, trial_allowance(feature) + net.get(feature, 0))


async def consume(
    db: AsyncSession,
    user_id: uuid.UUID,
    feature: str,
    *,
    session_id: uuid.UUID | None = None,
    detail: dict | None = None,
) -> CreditEvent | None:
    """
    Spend one of `feature`, or refuse.

    Raises CreditsExhaustedError (402) when there is nothing left. Returns the ledger row it
    appended to the CALLER'S transaction — deliberately not committed here.

    NONE MEANS NOTHING WAS CHARGED, which today is only the admin exemption below: admins are
    unmetered, so no row is written and there is nothing for a caller to attach a session to.
    A caller must therefore treat None as "no charge to annotate", never as an error.

    THE ROW IS RETURNED SO A CALLER THAT CANNOT KNOW THE SESSION YET CAN ATTACH IT, and that
    is not a convenience — it closes a hole that gave away paid reports. `/interview/plan`
    charges BEFORE generating, because the generation is the expensive part and an exhausted
    user must not pay for it; but the session does not exist until `create_plan` returns, so
    that call site could only ever charge with `session_id=None`. Report access is decided by
    finding the consume row for a session, and a charge with no session attached looks exactly
    like no charge at all — so `report_access` found nothing, failed open as designed, and
    handed over a free interview's report for nothing. Every interview begun through the plan
    flow was affected.

    So the caller charges, generates, and then sets `event.session_id` on the row it got back,
    all inside the one transaction that `get_db` commits. Charge-before-generation is kept, and
    the charge still ends up attributable to the session it paid for.

    THE CALLER MUST COMMIT, AND MUST COMMIT THE WORK IN THE SAME TRANSACTION. That is the
    contract, and it is what makes this atomic rather than merely careful: if starting the
    interview fails after this point, the rollback takes the charge with it. Committing here
    would create a window in which the user has been charged for a session that does not
    exist, and that window is exactly where a 500 lands.
    """
    # ADMINS ARE NOT METERED.
    #
    # Not a perk — it is the only way the product can be operated. Every check of whether
    # an interview still works, every reproduction of a reported bug, every demo, runs
    # through the same paths a candidate uses; metering them means the person answering
    # support tickets runs out of interviews on a Tuesday and starts testing on a spare
    # account, which is how a broken flow reaches production unnoticed.
    #
    # Checked before the balance rather than after, so no ledger row is written at all.
    # Recording admin usage as consumption would make the cost-per-user figures in
    # /ai-usage wrong in the direction of "our users are more expensive than they are",
    # which is the number the pricing rests on.
    if await _is_admin(db, user_id):
        # None, not a row: nothing was charged, so there is nothing for a caller to attach a
        # session to. See the docstring.
        return None

    # THE RETURN VALUE IS DISCARDED AND THIS CALL IS STILL ESSENTIAL. DO NOT REMOVE IT.
    #
    # `lock=True` takes `SELECT ... FOR UPDATE` on the user's row, and that lock is the entire
    # concurrency guarantee described at the top of this file: it is what makes a double-click
    # on Start Interview cost one interview instead of two. It reads as a useless call now that
    # nothing uses the row — which is exactly how somebody tidying up would delete it and
    # silently reintroduce double-spending, a bug that only appears under a race and always on
    # the expensive half.
    #
    # It used to be read for `is_banned`, which was the credential-sharing suspension's last
    # gate before anything billable. That feature is gone — see the long note in
    # core/security.py — and the column is now inert. Leaving the check in would have kept
    # previously-suspended accounts locked out of credits they had already paid for.
    await _plan_row(db, user_id, lock=True)

    net = await _totals(db, user_id)
    remaining = trial_allowance(feature) + net.get(feature, 0)

    if remaining <= 0:
        used_trial = trial_allowance(feature) > 0
        logger.info(
            "credits_exhausted",
            user_id=str(user_id),
            feature=feature,
            trial=trial_allowance(feature),
            net=net.get(feature, 0),
        )
        raise CreditsExhaustedError(feature, used_trial)

    # ── WAS THIS ONE FREE, OR PAID FOR? RECORDED, BECAUSE NOTHING ELSE CAN ANSWER IT LATER ──
    #
    # The product rule is "a free interview's report is payable; a purchased interview's report
    # is included". The price is `plans.REPORT_UNLOCK_PRICE_PAISE` and is deliberately not
    # restated here — an earlier draft of this comment said ₹49, which is the price of the
    # `interview_1` item and NOT of the report unlock, and plans.py carries a section titled
    # "WHY ₹50 AND NOT ₹49" explaining that the two numbers differ on purpose. A price copied
    # into a comment is a price that drifts from the constant the server actually charges.
    #
    # Deciding free-or-paid at report time is impossible from the ledger alone: a
    # consumption row is a `-1` and says nothing about which pot it came out of, and
    # `remaining = trial_allowance + net` is a single number that has already blended them.
    #
    # It IS knowable here, and only here. Consumption draws on the trial allowance first — that
    # is what `trial_allowance(feature) + net` means — so this consumption is free exactly when
    # fewer than `trial_allowance` have been consumed before it. One count, at the only moment
    # the answer exists.
    #
    # Stored in `detail`, which is JSONB, so this needs no migration and no model change. The
    # column's own comment says it is "room for anything the dispute needs later without a
    # migration"; this is that.
    #
    # THE READER MUST FAIL OPEN. A row written before this existed carries no `paid_with`, and
    # an unknown value has to mean "do not charge for the report" — never "charge". Locking a
    # report somebody has already paid for is the worst outcome available here, and it would
    # land on every interview taken before this deploy.
    consumed_before = await db.scalar(
        select(func.count())
        .select_from(CreditEvent)
        .where(
            CreditEvent.user_id == user_id,
            CreditEvent.feature == feature,
            CreditEvent.kind == KIND_CONSUME,
        )
    )
    paid_with = "trial" if (consumed_before or 0) < trial_allowance(feature) else "credit"

    event = CreditEvent(
        created_at=datetime.now(UTC),
        user_id=user_id,
        feature=feature,
        kind=KIND_CONSUME,
        delta=-1,
        session_id=session_id,
        # Merged rather than replaced: callers pass their own context here and none of it
        # should be lost to this addition.
        detail={**(detail or {}), "paid_with": paid_with},
    )
    db.add(event)
    await db.flush()
    return event


async def grant(
    db: AsyncSession,
    user_id: uuid.UUID,
    feature: str,
    quantity: int,
    *,
    kind: str = KIND_PURCHASE,
    payment_ref: str | None = None,
    #: WHICH SESSION THIS GRANT BELONGS TO, for entitlement that is not a stock.
    #:
    #: Every other purchasable thing here is a stock: buy five interviews, spend them on any
    #: five sessions. A report unlock is not — it belongs to ONE session's report and is
    #: meaningless anywhere else. `consume` has always taken this; `grant` did not, so a
    #: per-session entitlement could be sold and then not be recordable against the thing it
    #: was sold for. Found by a test that tried to grant one and could not.
    #:
    #: Optional and defaulting to None, so every existing caller — the webhook, the verify
    #: endpoint, admin goodwill — is unchanged and keeps writing a stock grant.
    session_id: uuid.UUID | None = None,
    detail: dict | None = None,
) -> bool:
    """
    Add `quantity` of `feature` to the ledger — a purchase, a refund, or admin goodwill.

    Returns True when it granted and False when this `payment_ref` had already been applied.

    IDEMPOTENCY IS THIS FUNCTION'S JOB NOW, AND IT USED TO BE THE CALLER'S. That sentence
    stood here for a long time — "IDEMPOTENCY IS THE CALLER'S JOB AND IS NOT OPTIONAL" — and
    both callers did it the same unsafe way, which is the argument against ever writing it
    again.

    WHAT THE CALLERS DID, AND WHY IT LOST. `/billing/verify` and the webhook each ran
    `SELECT id FROM credit_events WHERE payment_ref = ?`, and if it came back empty, granted.
    Under READ COMMITTED, with no lock, two concurrent requests both read empty and both
    insert — and the window between the read and the write is not small: `/verify` makes a
    live HTTP call to Razorpay inside it, roughly 300ms. `/verify` also has no rate limit. So
    an authenticated buyer could purchase one item and then fire the same
    payment_id/order_id/signature at `/verify` twenty times in parallel; every one passes the
    signature check, every one reads an empty ledger, and every one commits its own grant. The
    index on `payment_ref` is not unique, so nothing at the database stopped it either.

    It also double-credited HONEST customers. The webhook and `/verify` fire within
    milliseconds of the same capture and did not serialise against each other, so whichever
    lost the race still granted.

    THE LOCK, NOT A UNIQUE INDEX. A partial unique index on `payment_ref` is the other correct
    answer and is a better long-term shape — but it needs a migration, and a migration that
    fails on pre-existing duplicates fails the deploy. Locking the user's `user_plans` row is
    the pattern `consume` already uses for exactly this reason, needs no schema change, and is
    sufficient: a payment belongs to one user (ownership is checked before we get here), so
    two grants for one `payment_ref` are always two requests for the same user and always take
    the same lock. The index is worth adding later, without launch pressure, as belt and
    braces.

    Grants with NO `payment_ref` — admin goodwill, a refund — are not deduplicated, because
    there is nothing to deduplicate on and two acts of goodwill are two grants. They still take
    the lock, so they cannot interleave with a purchase for the same account.
    """
    if quantity <= 0:
        raise ValueError("grant quantity must be positive")

    # Serialises every grant for this user against every other. Must come BEFORE the
    # duplicate check, or the check races exactly as the callers' versions did.
    await _plan_row(db, user_id, lock=True)

    if payment_ref:
        already = await db.scalar(
            select(CreditEvent.id).where(CreditEvent.payment_ref == payment_ref).limit(1)
        )
        if already is not None:
            # Not an error. Razorpay redelivers until it gets a 2xx, and a client that retries
            # a verify is doing something reasonable — so the honest response is "already
            # applied", and the caller returns success without granting twice.
            logger.info(
                "credit_grant_already_applied",
                user_id=str(user_id),
                payment_ref=payment_ref,
                feature=feature,
            )
            return False
    db.add(
        CreditEvent(
            created_at=datetime.now(UTC),
            user_id=user_id,
            feature=feature,
            kind=kind,
            delta=quantity,
            payment_ref=payment_ref,
            session_id=session_id,
            detail=detail,
        )
    )
    await db.flush()
    return True

