"""
Checking and consuming a user's allowance — services/billing/credits.py

THIS IS THE ONLY PLACE ENTITLEMENT IS DECIDED. Endpoints call `consume`; nothing else reads
allowances to make a decision. A second implementation — a convenience check somewhere that
"just" compares a count — is how a metered feature ends up free on one route.

## Why this is server-side, and why hiding the button is not enough

The paywall in the UI is a courtesy to the user, not a control. Every metered endpoint is
reachable directly with a valid token, and a user who has spent their allowance is exactly
the user with a reason to try. The button being disabled costs an attacker one `curl`.

So the rule is: the UI may not show anything the server would refuse, and the server refuses
regardless of what the UI showed.

## Concurrency, which is the part that is easy to get wrong

The naive implementation is `count()`, compare, `insert()`. Two requests that interleave
between the count and the insert both see the same count and both pass — so the user on their
last free interview, double-clicking Start, gets two. That is not a theoretical race: a
double-submit on a slow connection is the single most common way it happens, and the report
generated by the second one is the expensive half.

`SELECT ... FOR UPDATE` on the user's plan row closes it. The plan row is the natural
serialisation point: exactly one exists per user, every consume path needs it anyway to know
the allowance, and taking a write lock on it means the second request blocks until the first
has committed its ledger row and can therefore see it. Concurrency is serialised per user and
nowhere else, so one candidate starting an interview never blocks another.

The whole check-and-write must therefore be in ONE transaction. Callers must not commit
between `consume` and the work it paid for.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta

import structlog
from fastapi import status
from sqlalchemy import func, select

from app.core.exceptions import AppError
from app.db.session import AsyncSession
from app.models.billing import CreditEvent, UserPlan
from app.services.billing.plans import (
    FEATURE_LABELS,
    FEATURES,
    UNLIMITED,
    allowance_for,
    get_plan,
)

logger = structlog.get_logger(__name__)

#: One billing period. Thirty days rather than a calendar month so every user's period is the
#: same length regardless of when they signed up — "8 interviews a month" meaning 8 per 28
#: days for a February signup and 8 per 31 days for a January one is a difference nobody
#: intends and somebody eventually notices.
_PERIOD = timedelta(days=30)


class CreditsExhaustedError(AppError):
    """
    The user has used everything this feature allows on their plan.

    402 PAYMENT REQUIRED, not 403. The distinction is load-bearing for the client: 403 means
    "you may not do this", which is permanent and offers nothing, while 402 means "you may do
    this once you pay", which is a prompt with an action attached. The frontend routes this
    status straight to the upgrade sheet, so getting it wrong shows a dead end where an offer
    belongs.

    `details` carries the machine-readable shape the paywall renders from, so the client never
    has to parse the message.
    """

    def __init__(self, feature: str, plan_id: str, used: int, allowance: int) -> None:
        label = FEATURE_LABELS.get(feature, feature)
        plan = get_plan(plan_id)
        super().__init__(
            message=(
                f"You have used all {allowance} {label} on the {plan.name} plan. "
                "Upgrade to keep going."
            ),
            status_code=status.HTTP_402_PAYMENT_REQUIRED,
            code="CREDITS_EXHAUSTED",
            details={
                "feature": feature,
                "plan_id": plan.id,
                "used": used,
                "allowance": allowance,
            },
        )


@dataclass(frozen=True)
class FeatureBalance:
    feature: str
    label: str
    used: int
    allowance: int

    @property
    def remaining(self) -> int:
        return max(0, self.allowance - self.used)

    @property
    def unlimited(self) -> bool:
        return self.allowance >= UNLIMITED


@dataclass(frozen=True)
class Balance:
    plan_id: str
    plan_name: str
    period_start: datetime
    period_end: datetime
    features: list[FeatureBalance]


async def _get_or_create_plan(
    db: AsyncSession, user_id: uuid.UUID, *, lock: bool
) -> UserPlan:
    """
    The user's plan row, creating a free one on first sight, and rolling the period over when
    it has expired.

    LAZY CREATION RATHER THAN A SIGNUP HOOK. Every user needs one of these and the signup path
    is not the only way a user row appears — the Supabase sync in POST /auth/profile creates
    them, admin tooling creates them, and a restored backup has them already. A row that is
    created on first read cannot be missed by any of those, and the alternative failure is a
    user who cannot start anything because a hook did not fire months ago.

    THE PERIOD ROLLS FORWARD HERE, not in a scheduled job. A cron that resets allowances is a
    single point of failure whose outage either locks everybody out or hands everybody
    unlimited use, and it fires for dormant users who will never log in. Rolling on read means
    the reset happens exactly when it can matter — when somebody asks — and cannot fail
    separately from the request that needed it.
    """
    stmt = select(UserPlan).where(UserPlan.user_id == user_id)
    if lock:
        stmt = stmt.with_for_update()
    plan_row = await db.scalar(stmt)

    now = datetime.now(UTC)

    if plan_row is None:
        plan_row = UserPlan(
            user_id=user_id,
            plan_id="free",
            period_start=now,
            period_end=now + _PERIOD,
            source="signup",
        )
        db.add(plan_row)
        # Flushed, not committed — the caller owns the transaction, and on the consume path
        # this row is what the lock above is taken on.
        await db.flush()
        return plan_row

    if plan_row.period_end <= now:
        # Rolled forward from the OLD end, not from now, so periods stay aligned to the
        # original anniversary. Anchoring to `now` would let a user who returns a day late
        # every month slowly walk their renewal date backwards through the calendar.
        #
        # Looped because a dormant user can be many periods behind, and advancing by one
        # would leave period_end in the past — the reset would then re-run on every single
        # request, and the ledger predicate would still be counting an ancient window.
        start = plan_row.period_end
        while start + _PERIOD <= now:
            start += _PERIOD
        plan_row.period_start = start
        plan_row.period_end = start + _PERIOD
        await db.flush()

    return plan_row


async def _used(
    db: AsyncSession, user_id: uuid.UUID, feature: str, since: datetime
) -> int:
    count = await db.scalar(
        select(func.count())
        .select_from(CreditEvent)
        .where(
            CreditEvent.user_id == user_id,
            CreditEvent.feature == feature,
            CreditEvent.created_at >= since,
        )
    )
    return int(count or 0)


async def get_balance(db: AsyncSession, user_id: uuid.UUID) -> Balance:
    """
    What this user has left, for every metered feature.

    Read-only and unlocked — this feeds the dashboard and the paywall copy, where a value one
    request out of date is harmless. `consume` does its own locked read and never trusts this.
    """
    plan_row = await _get_or_create_plan(db, user_id, lock=False)
    plan = get_plan(plan_row.plan_id)

    features = []
    for feature in FEATURES:
        allowance = allowance_for(plan.id, feature)
        used = await _used(db, user_id, feature, plan_row.period_start)
        features.append(
            FeatureBalance(
                feature=feature,
                label=FEATURE_LABELS[feature],
                used=used,
                allowance=allowance,
            )
        )

    return Balance(
        plan_id=plan.id,
        plan_name=plan.name,
        period_start=plan_row.period_start,
        period_end=plan_row.period_end,
        features=features,
    )


async def consume(
    db: AsyncSession,
    user_id: uuid.UUID,
    feature: str,
    *,
    session_id: uuid.UUID | None = None,
    detail: dict | None = None,
) -> None:
    """
    Charge one unit of `feature` to this user, or refuse.

    Raises CreditsExhaustedError (402) when the allowance is spent. Returns None on success,
    having added a ledger row to the CALLER'S transaction — deliberately not committed here.

    THE CALLER MUST COMMIT, AND MUST COMMIT THE WORK IN THE SAME TRANSACTION. That is the
    contract, and it is what makes this atomic rather than merely careful: if starting the
    interview fails after this point, the rollback takes the charge with it. Committing here
    would create a window in which the user has been charged for a session that does not
    exist, and that window is precisely where a 500 lands.

    UNLIMITED IS STILL RECORDED. A Pro user's communication drills do not count against
    anything, but the event is still written — usage data on the unmetered tiers is what tells
    you whether the next price change is safe, and it costs one insert.
    """
    plan_row = await _get_or_create_plan(db, user_id, lock=True)
    allowance = allowance_for(plan_row.plan_id, feature)

    if allowance < UNLIMITED:
        used = await _used(db, user_id, feature, plan_row.period_start)
        if used >= allowance:
            logger.info(
                "credits_exhausted",
                user_id=str(user_id),
                feature=feature,
                plan_id=plan_row.plan_id,
                used=used,
                allowance=allowance,
            )
            raise CreditsExhaustedError(feature, plan_row.plan_id, used, allowance)

    db.add(
        CreditEvent(
            created_at=datetime.now(UTC),
            user_id=user_id,
            feature=feature,
            session_id=session_id,
            plan_id=plan_row.plan_id,
            period_start=plan_row.period_start,
            detail=detail,
        )
    )
    await db.flush()
